"use strict";/*!
 * ***********************************
 * @ldesign/color v1.0.0           *
 * Built with rollup               *
 * Build time: 2024-10-21 14:32:31 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */var i=require("../utils/math.cjs"),o=require("./Color.cjs");function P(t,r=10,e={}){const{mode:a="lightness",curve:l="linear"}=e,n=new o.Color(t),s=n.toHSL(),m=Array.from({length:r},()=>null),f=n.alpha,c=1/(r-1),h=s.h,S=s.s,H=s.l;for(let g=0;g<r;g++){const M=g*c,x=G(M,l);let L=S,d=H;if((a==="lightness"||a==="both")&&(d=10+90*x),a==="saturation"||a==="both"){const $=Math.abs(x-.5)*2;L=S*(1-$*.3)}m[g]=o.Color.fromHSL(h,L,d,f)}return m}function G(t,r){switch(r){case"easeIn":return t*t;case"easeOut":return t*(2-t);case"easeInOut":return t<.5?2*t*t:-1+(4-2*t)*t;default:return t}}function u(t,r={}){const{lightSteps:e=[95,90,80,70,60],darkSteps:a=[40,30,20,10,5]}=r,l=new o.Color(t),n=l.toHSL(),s=Object.create(null),m=n.h,f=n.s;for(let c=0;c<e.length;c++)s[c+1]=o.Color.fromHSL(m,Math.max(10,f*(1-c*.1)),e[c]).toHex();s[6]=l.toHex();for(let c=0;c<a.length;c++)s[c+7]=o.Color.fromHSL(m,Math.min(100,f*(1+c*.05)),a[c]).toHex();return l.dispose(),s}function y(t){const r=new o.Color(t),e={success:120,warning:45,danger:0,info:200},a=r.toHSL(),l=a.s,n=a.l;return{primary:r.toHex(),success:o.Color.fromHSL(e.success,i.clamp(l*.9,40,90),i.clamp(n,35,65)).toHex(),warning:o.Color.fromHSL(e.warning,i.clamp(l*1.1,50,95),i.clamp(n*1.1,40,70)).toHex(),danger:o.Color.fromHSL(e.danger,i.clamp(l*.95,45,90),i.clamp(n*.95,35,60)).toHex(),info:o.Color.fromHSL(e.info,i.clamp(l*.85,35,85),i.clamp(n,40,65)).toHex()}}function w(t=10){const r=[];for(let e=0;e<t;e++){const a=e/(t-1)*100;r.push(o.Color.fromHSL(0,0,a))}return r}function b(t,r={}){const{generateScales:e=!0,includeGrays:a=!0,graySteps:l=10}=r,n=y(t),s={};if(e){if(s.primary=u(n.primary),s.success=u(n.success),s.warning=u(n.warning),s.danger=u(n.danger),s.info=u(n.info),a){const m=w(l);s.gray={},m.forEach((f,c)=>{s.gray[c+1]=f.toHex()})}}else s.primary=n.primary,s.success=n.success,s.warning=n.warning,s.danger=n.danger,s.info=n.info;return s}function C(t,r={}){const{prefix:e="--color",selector:a=":root",format:l="hex"}=r,n=[];function s(m,f=[]){if(typeof m=="string"){let c=m;if(l!=="hex"){const S=new o.Color(m);if(l==="rgb"){const H=S.toRGB();c=`${H.r}, ${H.g}, ${H.b}`}else if(l==="hsl"){const H=S.toHSL();c=`${Math.round(H.h)}, ${Math.round(H.s)}%, ${Math.round(H.l)}%`}}const h=`${e}-${f.join("-")}`;n.push(`  ${h}: ${c};`)}else typeof m=="object"&&m!==null&&Object.entries(m).forEach(([c,h])=>{s(h,[...f,c])})}return s(t),`${a} {
${n.join(`
`)}
}`}function p(t,r={}){if(typeof document>"u"){console.warn("insertCSSVariables: Not in a browser environment");return}const{id:e="ldesign-color-theme"}=r,a=document.getElementById(e);a&&a.remove();const l=C(t,r),n=document.createElement("style");n.id=e,n.textContent=l,document.head.appendChild(n)}function T(t,r={}){const{autoInsert:e=!1,...a}=r,l=b(t,{generateScales:r.generateScales,includeGrays:r.includeGrays}),n=C(l,{prefix:r.prefix,selector:r.selector,format:r.format});return e&&typeof document<"u"&&p(l,a),{theme:l,css:n,apply:()=>p(l,a)}}function j(t){const r=new o.Color(t),e=r.toHSL(),a={50:o.Color.fromHSL(e.h,e.s*.12,97).toHex(),100:o.Color.fromHSL(e.h,e.s*.3,93).toHex(),200:o.Color.fromHSL(e.h,e.s*.5,82).toHex(),300:o.Color.fromHSL(e.h,e.s*.7,68).toHex(),400:o.Color.fromHSL(e.h,e.s*.85,58).toHex(),500:r.toHex(),600:o.Color.fromHSL(e.h,e.s*1.05,45).toHex(),700:o.Color.fromHSL(e.h,e.s*1.1,36).toHex(),800:o.Color.fromHSL(e.h,e.s*1.15,28).toHex(),900:o.Color.fromHSL(e.h,e.s*1.2,18).toHex()};return e.s>50&&(a.A100=o.Color.fromHSL(e.h,Math.min(100,e.s*1.2),80).toHex(),a.A200=o.Color.fromHSL(e.h,Math.min(100,e.s*1.3),65).toHex(),a.A400=o.Color.fromHSL(e.h,Math.min(100,e.s*1.4),55).toHex(),a.A700=o.Color.fromHSL(e.h,Math.min(100,e.s*1.5),45).toHex()),a}function v(t){const r=new o.Color(t),e=r.toHSL();return{50:o.Color.fromHSL(e.h,i.clamp(e.s*.33,10,100),97).toHex(),100:o.Color.fromHSL(e.h,i.clamp(e.s*.44,10,100),94).toHex(),200:o.Color.fromHSL(e.h,i.clamp(e.s*.6,10,100),86).toHex(),300:o.Color.fromHSL(e.h,i.clamp(e.s*.77,10,100),77).toHex(),400:o.Color.fromHSL(e.h,i.clamp(e.s*.92,10,100),63).toHex(),500:r.toHex(),600:o.Color.fromHSL(e.h,i.clamp(e.s*1.08,10,100),42).toHex(),700:o.Color.fromHSL(e.h,i.clamp(e.s*1.15,10,100),33).toHex(),800:o.Color.fromHSL(e.h,i.clamp(e.s*1.23,10,100),27).toHex(),900:o.Color.fromHSL(e.h,i.clamp(e.s*1.3,10,100),22).toHex(),950:o.Color.fromHSL(e.h,i.clamp(e.s*1.38,10,100),13).toHex()}}exports.applyTheme=T,exports.generateCSSVariables=C,exports.generateGrayScale=w,exports.generateMaterialPalette=j,exports.generateNumberedPalette=u,exports.generateScale=P,exports.generateSemanticColors=y,exports.generateTailwindPalette=v,exports.generateThemePalette=b,exports.insertCSSVariables=p;/*! End of @ldesign/color | Powered by @ldesign/builder */
//# sourceMappingURL=palette.cjs.map
