/*!
 * ***********************************
 * @ldesign/color v1.0.0           *
 * Built with rollup               *
 * Build time: 2024-10-21 14:32:31 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{clamp as f}from"../utils/math.js";import{Color as t}from"./Color.js";function j(o,r=10,e={}){const{mode:s="lightness",curve:c="linear"}=e,n=new t(o),a=n.toHSL(),H=Array.from({length:r},()=>null),m=n.alpha,i=1/(r-1),l=a.h,S=a.s,u=a.l;for(let x=0;x<r;x++){const M=x*i,d=A(M,c);let p=S,y=u;if((s==="lightness"||s==="both")&&(y=10+90*d),s==="saturation"||s==="both"){const C=Math.abs(d-.5)*2;p=S*(1-C*.3)}H[x]=t.fromHSL(l,p,y,m)}return H}function A(o,r){switch(r){case"easeIn":return o*o;case"easeOut":return o*(2-o);case"easeInOut":return o<.5?2*o*o:-1+(4-2*o)*o;default:return o}}function h(o,r={}){const{lightSteps:e=[95,90,80,70,60],darkSteps:s=[40,30,20,10,5]}=r,c=new t(o),n=c.toHSL(),a=Object.create(null),H=n.h,m=n.s;for(let i=0;i<e.length;i++)a[i+1]=t.fromHSL(H,Math.max(10,m*(1-i*.1)),e[i]).toHex();a[6]=c.toHex();for(let i=0;i<s.length;i++)a[i+7]=t.fromHSL(H,Math.min(100,m*(1+i*.05)),s[i]).toHex();return c.dispose(),a}function w(o){const r=new t(o),e={success:120,warning:45,danger:0,info:200},s=r.toHSL(),c=s.s,n=s.l;return{primary:r.toHex(),success:t.fromHSL(e.success,f(c*.9,40,90),f(n,35,65)).toHex(),warning:t.fromHSL(e.warning,f(c*1.1,50,95),f(n*1.1,40,70)).toHex(),danger:t.fromHSL(e.danger,f(c*.95,45,90),f(n*.95,35,60)).toHex(),info:t.fromHSL(e.info,f(c*.85,35,85),f(n,40,65)).toHex()}}function b(o=10){const r=[];for(let e=0;e<o;e++){const s=e/(o-1)*100;r.push(t.fromHSL(0,0,s))}return r}function $(o,r={}){const{generateScales:e=!0,includeGrays:s=!0,graySteps:c=10}=r,n=w(o),a={};if(e){if(a.primary=h(n.primary),a.success=h(n.success),a.warning=h(n.warning),a.danger=h(n.danger),a.info=h(n.info),s){const H=b(c);a.gray={},H.forEach((m,i)=>{a.gray[i+1]=m.toHex()})}}else a.primary=n.primary,a.success=n.success,a.warning=n.warning,a.danger=n.danger,a.info=n.info;return a}function g(o,r={}){const{prefix:e="--color",selector:s=":root",format:c="hex"}=r,n=[];function a(H,m=[]){if(typeof H=="string"){let i=H;if(c!=="hex"){const S=new t(H);if(c==="rgb"){const u=S.toRGB();i=`${u.r}, ${u.g}, ${u.b}`}else if(c==="hsl"){const u=S.toHSL();i=`${Math.round(u.h)}, ${Math.round(u.s)}%, ${Math.round(u.l)}%`}}const l=`${e}-${m.join("-")}`;n.push(`  ${l}: ${i};`)}else typeof H=="object"&&H!==null&&Object.entries(H).forEach(([i,l])=>{a(l,[...m,i])})}return a(o),`${s} {
${n.join(`
`)}
}`}function L(o,r={}){if(typeof document>"u"){console.warn("insertCSSVariables: Not in a browser environment");return}const{id:e="ldesign-color-theme"}=r,s=document.getElementById(e);s&&s.remove();const c=g(o,r),n=document.createElement("style");n.id=e,n.textContent=c,document.head.appendChild(n)}function G(o,r={}){const{autoInsert:e=!1,...s}=r,c=$(o,{generateScales:r.generateScales,includeGrays:r.includeGrays}),n=g(c,{prefix:r.prefix,selector:r.selector,format:r.format});return e&&typeof document<"u"&&L(c,s),{theme:c,css:n,apply:()=>L(c,s)}}function E(o){const r=new t(o),e=r.toHSL(),s={50:t.fromHSL(e.h,e.s*.12,97).toHex(),100:t.fromHSL(e.h,e.s*.3,93).toHex(),200:t.fromHSL(e.h,e.s*.5,82).toHex(),300:t.fromHSL(e.h,e.s*.7,68).toHex(),400:t.fromHSL(e.h,e.s*.85,58).toHex(),500:r.toHex(),600:t.fromHSL(e.h,e.s*1.05,45).toHex(),700:t.fromHSL(e.h,e.s*1.1,36).toHex(),800:t.fromHSL(e.h,e.s*1.15,28).toHex(),900:t.fromHSL(e.h,e.s*1.2,18).toHex()};return e.s>50&&(s.A100=t.fromHSL(e.h,Math.min(100,e.s*1.2),80).toHex(),s.A200=t.fromHSL(e.h,Math.min(100,e.s*1.3),65).toHex(),s.A400=t.fromHSL(e.h,Math.min(100,e.s*1.4),55).toHex(),s.A700=t.fromHSL(e.h,Math.min(100,e.s*1.5),45).toHex()),s}function I(o){const r=new t(o),e=r.toHSL();return{50:t.fromHSL(e.h,f(e.s*.33,10,100),97).toHex(),100:t.fromHSL(e.h,f(e.s*.44,10,100),94).toHex(),200:t.fromHSL(e.h,f(e.s*.6,10,100),86).toHex(),300:t.fromHSL(e.h,f(e.s*.77,10,100),77).toHex(),400:t.fromHSL(e.h,f(e.s*.92,10,100),63).toHex(),500:r.toHex(),600:t.fromHSL(e.h,f(e.s*1.08,10,100),42).toHex(),700:t.fromHSL(e.h,f(e.s*1.15,10,100),33).toHex(),800:t.fromHSL(e.h,f(e.s*1.23,10,100),27).toHex(),900:t.fromHSL(e.h,f(e.s*1.3,10,100),22).toHex(),950:t.fromHSL(e.h,f(e.s*1.38,10,100),13).toHex()}}/*! End of @ldesign/color | Powered by @ldesign/builder */export{G as applyTheme,g as generateCSSVariables,b as generateGrayScale,E as generateMaterialPalette,h as generateNumberedPalette,j as generateScale,w as generateSemanticColors,I as generateTailwindPalette,$ as generateThemePalette,L as insertCSSVariables};
//# sourceMappingURL=palette.js.map
