"use strict";/*!
 * ***********************************
 * @ldesign/color v1.0.0           *
 * Built with rollup               *
 * Build time: 2024-10-21 14:32:31 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */var l=require("vue"),t=require("react"),b=require("../themes/presets.cjs"),k=require("../themes/themeManager.cjs");function M(s){return typeof s=="function"||Object.prototype.toString.call(s)==="[object Object]"&&!l.isVNode(s)}function c(s={}){const r=t.useMemo(()=>new k.ThemeManager(s),[]),[e,o]=t.useState(null),[h,m]=t.useState(!1),T=t.useMemo(()=>e?.primaryColor||"",[e]),p=t.useMemo(()=>e?.themeName||"",[e]),f=t.useMemo(()=>e?.isDark||!1,[e]),y=t.useCallback(async(n,a)=>{m(!0);try{const u=r.applyTheme(n,a);return o(u),u}finally{m(!1)}},[r]),C=t.useCallback(async(n,a)=>{m(!0);try{const u=r.applyPresetTheme(n,a);return o(u),u}finally{m(!1)}},[r]),d=t.useCallback(()=>{const n=r.restore();return n&&o(n),n},[r]),v=t.useCallback(()=>{r.clear(),o(null)},[r]),g=t.useCallback(()=>{const n=r.getCurrentTheme();return o(n),n},[r]);return t.useEffect(()=>{if(s.immediate!==!1){const a=r.getCurrentTheme()||r.restore();a&&o(a)}const n=r.onChange(a=>{o(a)});return()=>{n(),r&&typeof r.destroy=="function"&&r.destroy()}},[]),{currentTheme:e,presets:b.presetThemes,isLoading:h,primaryColor:T,themeName:p,isDark:f,applyTheme:y,applyPresetTheme:C,restoreTheme:d,clearTheme:v,getCurrentTheme:g}}const i=t.createContext(void 0);function P({children:s,options:r={}}){const e=c(r),o=t.useMemo(()=>e,[e.currentTheme,e.isLoading,e.primaryColor,e.themeName,e.isDark,e.applyTheme,e.applyPresetTheme,e.restoreTheme,e.clearTheme,e.getCurrentTheme]);return l.createVNode(i.Provider,{value:o},M(s)?s:{default:()=>[s],_:2},8,["value"])}function x(){const s=t.useContext(i);if(!s)throw new Error("useThemeContext must be used within a ThemeProvider");return s}exports.ThemeProvider=P,exports.useTheme=c,exports.useThemeContext=x;/*! End of @ldesign/color | Powered by @ldesign/builder */
//# sourceMappingURL=useTheme.cjs.map
