/*!
 * ***********************************
 * @ldesign/color v1.0.0           *
 * Built with rollup               *
 * Build time: 2024-10-21 14:32:31 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */import{defineComponent as T,ref as f,inject as U,computed as u,watch as k,createElementBlock as r,onMounted as j,onUnmounted as F,openBlock as l,createElementVNode as g,createVNode as S,createBlock as y,resolveDynamicComponent as B,toDisplayString as N,unref as V,normalizeClass as z,Transition as H,withCtx as Q,createCommentVNode as A,withModifiers as R,Fragment as Y,renderList as G}from"vue";import{Sun as D,Moon as J,Monitor as O,ChevronDown as P,Check as W}from"lucide-vue-next";import{getLocale as X}from"../locales/index.js";const Z={class:"theme-mode-switcher"},$=["title"],ee={class:"theme-label"},te=["onClick"],ae={class:"option-label"};var le=T({__name:"VueThemeModeSwitcher",props:{defaultMode:{type:String,required:!1},storageKey:{type:String,required:!1}},emits:["update:mode","change"],setup(I,{emit:K}){const i=I,b=K,w=i.storageKey||"ld-theme-mode",o=f(!1),t=f("system"),s=f("light"),m=U("locale",null),C=u(()=>m&&m.value?m.value:"zh-CN"),d=u(()=>X(C.value));k(C,e=>{});const c=u(()=>[{value:"light",label:d.value.themeMode.light,icon:D},{value:"dark",label:d.value.themeMode.dark,icon:J},{value:"system",label:d.value.themeMode.system,icon:O}]),M=u(()=>c.value.find(e=>e.value===t.value)?.label||"\u4E3B\u9898"),_=u(()=>c.value.find(e=>e.value===t.value)?.icon||D),L=u(()=>t.value==="system"?s.value:t.value),v=window.matchMedia("(prefers-color-scheme: dark)"),h=()=>{s.value=v.matches?"dark":"light"},p=e=>{const a=document.documentElement;e==="dark"?a.setAttribute("theme-mode","dark"):a.removeAttribute("theme-mode"),a.setAttribute("data-theme-mode",e),a.classList.remove("light","dark"),a.classList.add(e)},q=()=>{o.value=!o.value},x=e=>{t.value=e,localStorage.setItem(w,e),o.value=!1,b("update:mode",e),b("change",e)},E=e=>{e.target.closest(".theme-mode-switcher")||(o.value=!1)};return k(L,e=>{p(e)}),k(s,()=>{t.value==="system"&&p(s.value)}),j(()=>{h(),v.addEventListener("change",h);const e=localStorage.getItem(w);e&&c.value.some(a=>a.value===e)?t.value=e:i.defaultMode&&(t.value=i.defaultMode),p(L.value),document.addEventListener("click",E)}),F(()=>{v.removeEventListener("change",h),document.removeEventListener("click",E)}),(e,a)=>(l(),r("div",Z,[g("button",{class:"theme-mode-button",title:M.value,onClick:q},[(l(),y(B(_.value),{class:"theme-icon"})),g("span",ee,N(M.value),1),S(V(P),{class:z(["arrow",{open:o.value}])},null,8,["class"])],8,$),S(H,{name:"dropdown"},{default:Q(()=>[o.value?(l(),r("div",{key:0,class:"theme-dropdown",onClick:a[0]||(a[0]=R(()=>{},["stop"]))},[(l(!0),r(Y,null,G(c.value,n=>(l(),r("button",{key:n.value,class:z(["theme-option",{active:t.value===n.value}]),onClick:oe=>x(n.value)},[(l(),y(B(n.icon),{class:"option-icon"})),g("span",ae,N(n.label),1),t.value===n.value?(l(),y(V(W),{key:0,class:"check-icon"})):A("v-if",!0)],10,te))),128))])):A("v-if",!0)]),_:1})]))}});/*! End of @ldesign/color | Powered by @ldesign/builder */export{le as default};
//# sourceMappingURL=VueThemeModeSwitcher.vue2.js.map
